services:
  # app:
  #   build: .
  #   restart: unless-stopped
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT="http://lgtm:4317"
  #     - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT="http://lgtm:4317"
  #     - OTEL_METRIC_EXPORT_INTERVAL="5000"
  #     - OTEL_SERVICE_NAME="hello-nina-world"
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - lgtm
  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm
    ports:
      - "3000:3000" # Grafana
      - "3100:3100" # Loki
      - "3200:3200" # Tempo
      - "9090:9090" # Mimir / Prometheus
      - "4317:4317" # OpenTelemetry Collector (gRPC) 
      - "4318:4318" # OpenTelemetry Collector (HTTP) Not able to test