services:
  # 1. OTel Collector (O Porteiro)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./infra/local/config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # gRPC (Go usa esse)
      - "4318:4318" # HTTP
      - "8889:8889" # Prometheus metrics

  # 2. Tempo (Banco de Dados de Traces)
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./infra/local/config/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "4317"

  prometheus:
    image: prom/prometheus:latest
    command: [--config.file=/etc/prometheus/prometheus.yaml]
    volumes:
      - ./infra/local/config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  # 3. Grafana (Visualização)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./infra/local/config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - tempo
      - prometheus
  backend-go:
    build:
      context: ./apps/backend-go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - otel-collector

networks:
  default:
    name: lab-net
